name: pci_id
description: >-
  A repository of all known ID's used in PCI devices: ID's of vendors,
  devices, subsystems and device classes. This package can be utilized
  to display human-readable names instead of cryptic numeric codes.
homepage: https://pci-ids.ucw.cz/
repository: https://github.com/jpnurmi/pci_id.dart
issue_tracker: https://github.com/jpnurmi/pci_id.dart/issues
version: 0.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  equatable: ^2.0.0
  path: ^1.8.0
  quiver: ^3.0.1

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
